Repository JCKelley-CYBR/CYBR-8420-SoftwareAssurance, pull requests merged in 2022-10, with the labels that each got.

#82 Assurance case A3 Folders/Documents
  AssuranceCases.md
  AssuranceCases/README.md
Labels: enhancement

#84 Adding Claim 2/3
  AssuranceCases.md
  AssuranceCases/Credential_Confidentiality/CredentialConfidentiality.drawio
  AssuranceCases/Credential_Confidentiality/CredentialConfidentiality.png
  AssuranceCases/Credential_Confidentiality/README.md
  AssuranceCases/MaliciousUserInput/MaliciousUserInput.drawio
  AssuranceCases/MaliciousUserInput/MaliciousUserInput.drawio.png
  AssuranceCases/MaliciousUserInput/MaliciousUserInputV2.drawio
  AssuranceCases/MaliciousUserInput/MaliciousUserInputV2.drawio.png
  AssuranceCases/MaliciousUserInput/README.md
  AssuranceCases/README.md
  README.md
Labels: documentation

#90 Added Team Reflection
  AssuranceCases.md
Labels: documentation

#92 Update AssuranceCases.md
  AssuranceCases.md
Labels: bug

#94 Adding Aaron Overview
  AssuranceCases.md
Labels: documentation
